version: '3'
services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - srda-pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./
    # restart: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
    ports:
      - 3001:5000
    depends_on:
      - postgres

  webui:
    build:
      context: ./webui
    restart: always
    ports:
      - 3000:3000
volumes:
  srda-pgdata: